name: SolarSystem Workflow
on:
 workflow_dispatch: 
 push:
    branches: 
      - 'main'
      - 'feature/**'


jobs:
  unit_Testing:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest , macos-latest]
        node-version: [20,22,24]
        exclude:
         - os: macos-latest
           node-version: 20
    steps:
        - name: Checkout The Repo
          uses: actions/checkout@v4
        
        - name: Setup Node.js environment
          uses: actions/setup-node@v5
          with:
            node-version: ${{matrix.node-version}}
          
        - name: Installing Dependecies
          run: npm install
          
        - name: unit Testing
          run: npm test
        
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: mocha-test-result
            path: test-result.xml  # name of the file in the root directory    