name: SolarSystem Workflow
on:
 workflow_dispatch: 
 push:
    branches: 
      - 'main'
      - 'feature/**'
jobs:
  unit_Testing:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout The Repo
          uses: actions/checkout@v4
        
        - name: Setup Node.js environment
          uses: actions/setup-node@v5
          with:
            node-version: 20
         
        - name: Installing Dependecies
          run: npm install
          
        - name: unit Testing
          run: npm test